### ISSUE TITLE
Create the wso2.com page of the Ballerina VS Code plugin 

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-ballerina-vscode-extension#125]
**Description:**
Copied from https://github.com/ballerina-platform/ballerina-dev-website/issues/6135

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
From Ballerina's point of view, the [Ballerina VS Code docs](https://wso2.com/ballerina/vscode/docs/) linked from the VS Code marketplace and [ballerina.io](http://ballerina.io/) seems enough for Ballerina users.
