### ISSUE TITLE
Update Ballerina VS Code extension marketplace docs 

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-ballerina-vscode-extension#126]
**Description:**
Need to update the Ballerina VS Code extension marketplace docs in https://marketplace.visualstudio.com/items?itemName=WSO2.ballerina.

Created to track https://github.com/ballerina-platform/ballerina-dev-website/issues/6292

**Comment by praneesha** [comment]
Updated in https://marketplace.visualstudio.com/items?itemName=WSO2.ballerina.
