### ISSUE TITLE
Large gap between titles and content

### ISSUE THREAD

**Issue by SumayyaZiyad** [wso2/docs-ballerina-vscode-extension#138]
**Description:**
$subject was noticed in many pages. For example, refer to the below screenshots from the Notebook section.

<img width="1509" alt="Screenshot 2023-02-09 at 10 01 49 AM" src="https://user-images.githubusercontent.com/36619740/217722627-0ce55369-938b-446f-b2d2-dfd098daca53.png">

<img width="1508" alt="Screenshot 2023-02-09 at 10 01 45 AM" src="https://user-images.githubusercontent.com/36619740/217722617-cea83659-8cd1-4ea2-a246-3df1a8669712.png">

**Comment by praneesha** [comment]
Will be fixed via https://github.com/wso2/docs-ballerina-vscode-extension/pull/140.
