### ISSUE TITLE
Favicon and cookie policy bar displayed in orange color

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-ballerina-vscode-extension#208]
**Description:**
$subject.

<img width="1505" alt="image" src="https://github.com/wso2/docs-ballerina-vscode-extension/assets/16300038/17857ca6-e642-427e-ae83-10190c781dc9">

**Comment by praneesha** [comment]
The Cookie Pro color theme is kept to match the WSO2 theme. We have the same in WSO2 Choreo docs as well[1].

@keizer619 - Are we able to customize the colors as we use the WSO2 Cookie Pro account across all doc sites?

Will fix the favicon icon.

[1] https://wso2.com/choreo/

**Comment by keizer619** [comment]
@praneesha Need to check with thimuth AFAIK its not possible as its set for wso2.com domain

**Comment by praneesha** [comment]
Closing as the docs are moved to B.io now at: https://ballerina.io/learn/vs-code-extension/
