### ISSUE TITLE
Add page on ER diagram capabilities in the plugin

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-ballerina-vscode-extension#270]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Done in https://ballerina.io/learn/vs-code-extension/implement-the-code/entity-relationship-diagram-view/.
