### ISSUE TITLE
Improve the debugging page

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-ballerina-vscode-extension#72]
**Description:**

This is regarding the [Debug Ballerina code](https://wso2.com/ballerina/vscode/docs/debug-ballerina-code/) page.

It seems the following sub sections are more or less the same. Titles are also confusing as those are similar. Consider merging the content.

[Debug using configurations](https://wso2.com/ballerina/vscode/docs/debug-ballerina-code/#debug-using-configurations)
[Use debug configurations](https://wso2.com/ballerina/vscode/docs/debug-ballerina-code/#use-debug-configurations)

**Comment by praneesha** [comment]
Fixed via https://wso2.com/ballerina/vscode/docs/debug-the-code/.
