### ISSUE TITLE
Add documentation on AI test data generation

### ISSUE THREAD

**Issue by praneesha** [wso2/docs-ballerina-vscode-extension#85]
**Description:**
Need to add documentation on AI test data generation.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadheesh** [comment]
@praneesha is there any updates on this?

**Comment by praneesha** [comment]
> @praneesha is there any updates on this?

We will work on this with the doc updates of the VS Code extension 4.0 release.

@keizer619 @hevayo @kaviththiranga @gigara

**Comment by praneesha** [comment]
Done via https://github.com/wso2/docs-ballerina-vscode-extension/pull/175.

@nadheesh

**Comment by nadheesh** [comment]
@praneesha ack and thank you!
